ShoppingCore/Controllers/ShoppingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ShoppingCore.Models;
using ShoppingCore.Repository;

namespace ShoppingCore.Controllers
{
    [Authorize]
    public class ShoppingController : Controller
    {

        private IGenericRepository<Tbl_Product> prod_repository = null;

        public IGenericRepository<Tbl_Cart> Cart_repository = null;

        public IGenericRepository<Tbl_ProductImage> ProdImage_Repository { get; }
        public IHttpContextAccessor HttpContextAccessor { get; }
        public IGenericRepository<Tbl_ShippingDetails> Shippingrepository { get; }

        public ShoppingController(IGenericRepository<Tbl_Product> Prod_repository, IGenericRepository<Tbl_Cart> Cart_repository,
            IGenericRepository<Tbl_ProductImage> ProdImage_repository, IHttpContextAccessor HttpContextAccessor,
            IGenericRepository<Tbl_ShippingDetails> _shippingrepository)
        {
            this.prod_repository = Prod_repository;
            this.Cart_repository = Cart_repository;
            this.ProdImage_Repository = ProdImage_repository;
            this.HttpContextAccessor = HttpContextAccessor;
            Shippingrepository = _shippingrepository;
        }

        public IActionResult Cart()
        {
            return View();
        }

        public JsonResult CartData()
        {
            var memberid = User.FindFirstValue(ClaimTypes.Sid);
            List<Tbl_Product> product = new List<Tbl_Product>();
            IEnumerable<Tbl_Cart> cart = Cart_repository.GetListByParameter(i => i.CartStatusId == 1 && i.MemberId==Convert.ToInt32(memberid));

            foreach (var item in cart)
            {
                int _count = cart.Where(x => x.ProductId == item.ProductId).Count();
                Tbl_Product tbl_Product = new Tbl_Product();
                tbl_Product = prod_repository.GetById(item.ProductId);
                Tbl_ProductImage img = new Tbl_ProductImage();
                img = ProdImage_Repository.GetByParameter(i => i.ProductId == item.ProductId);
                tbl_Product.ProductImage = img.ImageName;
                tbl_Product.TotalProduct = _count;
                if (product.Any(s => s.ProductId == item.ProductId))
                    continue;
                product.Add(tbl_Product);
            }
            ViewBag.TotalPrice = product.Sum(i => i.PriceSale * i.TotalProduct);
            //ViewBag.TotalPrice = product.Sum(i => i.PriceSale);
            return Json(product);
        }

        [AllowAnonymous]
        public IActionResult _Cart()
        {
            ProductDetail tbl_Product = new ProductDetail();
            if (User.Identity.IsAuthenticated)
            {
                var memberid = User.FindFirstValue(ClaimTypes.Sid);
                tbl_Product.count = Cart_repository.GetAllRecordsCountByParameter(i => i.MemberId == Convert.ToInt32(memberid));
                return PartialView("_Cart", tbl_Product);
            }
            else
            {
                tbl_Product.count = 0;
                return PartialView("_Cart", tbl_Product);
            }
        }

        public int AddProductToCart(int itemId)
        {
            var memberid = User.FindFirstValue(ClaimTypes.Sid);
            Tbl_Cart tbl_Cart = new Tbl_Cart();
            tbl_Cart.AddedOn = DateTime.Now;
            tbl_Cart.CartStatusId = 1;
            tbl_Cart.MemberId = Convert.ToInt32(memberid);
            tbl_Cart.ProductId = itemId;
            tbl_Cart.UpdatedOn = DateTime.Now;
            Cart_repository.Insert(tbl_Cart);
            Cart_repository.Save();
            return 1;
        }

        public IActionResult AddProductToCart1(int itemId)
        {
            var memberid = User.FindFirstValue(ClaimTypes.Sid);
            Tbl_Cart tbl_Cart = new Tbl_Cart();
            tbl_Cart.AddedOn = DateTime.Now;
            tbl_Cart.CartStatusId = 1;
            tbl_Cart.MemberId = Convert.ToInt32(memberid);
            tbl_Cart.ProductId = itemId;
            tbl_Cart.UpdatedOn = DateTime.Now;
            Cart_repository.Insert(tbl_Cart);
            Cart_repository.Save();
            //TempData["ProductAddedToCart"] = "Product added to cart successfully";
            return RedirectToAction("Cart");
        }

        public int RemoveCart(int itemId)
        {
            Cart_repository.RemovebyWhereClause(i => i.ProductId == itemId);
            Cart_repository.Save();
            return 1;
        }

        public IActionResult Checkout()
        {
            List<Tbl_Product> product = new List<Tbl_Product>();
            var memberid = User.FindFirstValue(ClaimTypes.Sid);
            IEnumerable<Tbl_Cart> cart = Cart_repository.GetListByParameter(i => i.MemberId == Convert.ToInt32(memberid));
            foreach (var item in cart)
            {
                Tbl_Product tbl_Product = new Tbl_Product();
                tbl_Product = prod_repository.GetById(item.ProductId);
                product.Add(tbl_Product);
            }
            Shippingdetail shippingdetail = new Shippingdetail();
            shippingdetail.AmountPaid = product.Sum(i => i.PriceSale);
            return View(shippingdetail);
        }
        public ActionResult PaymentSuccess(Shippingdetail shippingDetails)
        {
            int memberid = Convert.ToInt32(User.FindFirstValue(ClaimTypes.Sid));
            IEnumerable<Tbl_Cart> carts = null;
            carts = Cart_repository.GetListByParameter(j => j.MemberId == memberid);
            foreach (var item in carts)
            {
                Tbl_ShippingDetails sd = new Tbl_ShippingDetails();
                sd.ProductId = item.ProductId;
                sd.AmountPaid = prod_repository.GetByParameter(i => i.ProductId == item.ProductId).PriceSale;
                sd.MemberId = item.MemberId;
                sd.RecieverName = shippingDetails.RecieverName;
                sd.Mobile = shippingDetails.Mobile;
                sd.AddressLine = shippingDetails.Adress;
                sd.City = shippingDetails.City;
                sd.State = shippingDetails.State;
                sd.Country = shippingDetails.Country;
                sd.ZipCode = shippingDetails.ZipCode;
                sd.OrderId = Guid.NewGuid().ToString();
                sd.PaymentType = shippingDetails.PaymentType;
                sd.OrderDate = shippingDetails.OrderDate;
                Shippingrepository.Insert(sd);
                Cart_repository.RemovebyWhereClause(i => i.MemberId == memberid && i.ProductId == item.ProductId);
                //prod_repository.UpdateByWhereClause(i => i.ProductId==item.ProductId, (j => j. = 3));

            }
            return RedirectToAction("Orders");
        }

        public ActionResult Orders()
        {
            int memberid = Convert.ToInt32(User.FindFirstValue(ClaimTypes.Sid));
            IEnumerable<Tbl_ShippingDetails> _ShippingDetails = null;
            List<Shippingdetail> shippingdetails = new List<Shippingdetail>();
            _ShippingDetails = Shippingrepository.GetListByParameter(i => i.MemberId == memberid);
            foreach (var item in _ShippingDetails)
            {
                Shippingdetail SD = new Shippingdetail();
                SD.AmountPaid = item.AmountPaid;
                SD.RecieverName = item.RecieverName;
                SD.ProductName = prod_repository.GetByParameter(i => i.ProductId == item.ProductId).ProductName;
                SD.Image = ProdImage_Repository.GetByParameter(i => i.ProductId == item.ProductId).ImageName;
                SD.Adress = item.AddressLine;
                SD.City = item.City;
                SD.Country = item.Country;
                SD.MemberId = item.MemberId;
                SD.Mobile = item.Mobile;
                SD.OrderId = item.OrderId;
                SD.PaymentType = item.PaymentType;
                SD.ProductId = item.ProductId;
                SD.State = item.State;
                SD.ZipCode = item.ZipCode;
                SD.OrderDate = item.OrderDate;
                shippingdetails.Add(SD);
            }
            return View(shippingdetails);
        }
    }
}

ShoppingCore/Views/Shared/Login.cshtml
@model ShoppingCore.Models.LoginViewModel
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{
    ViewData["Title"] = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="main-content-wrapper">
    <div class="main-title">
        <p class="custom-font-1">Login</p>
    </div>
    <div class="single-full-width">
        <div class="contact-form">
            <form asp-action="Login" asp-controller="Account" asp-route-returnurl="@Context.Request.Query["ReturnUrl"]" style="margin: 0 45px 0 100px;text-align:center;">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <p>
                    <label>E-mail:</label>
                    <input asp-for="UserEmailId" class="input-text-1" placeholder="E-mail" /><br />
                    <span asp-validation-for="UserEmailId" class="text-danger"></span>
                </p>

                <p>
                    <label>Password:</label>
                    <input asp-for="Password" class="input-text-1" placeholder="Password" /><br />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </p>
                <div class="form-group">
                    <input type="submit" value="Login" class="btn btn-primary" style="float: right;background-color: black;color: antiquewhite;padding: 5px 11px;border-radius: 8px;cursor:pointer" /><br /><br />
                    <a asp-controller="Account" asp-action="Register" style="font-size: large;text-decoration: underline;float:left">New User</a>
                </div>
            </form>

        </div>
        <div class="clear"></div>
        <!-- END .single-full-width -->
    </div>
    <div class="clear"></div>

    <div class="clear"></div>

</div>
<style>
    .contact-form .input-text-1 {
        padding: 0px 10px;
        opacity: 0.85;
        width: 450px;
        margin-left: 50px;
    }

    .contact-form form p {
        margin: 0 0 16px 95px;
        overflow: hidden;
        text-align: start;
        padding: 0 0 1px 0;
    }

    .contact-form form p {
        margin: 0 0 16px 0;
        overflow: hidden;
        padding: 0 0 1px 0;
    }
</style>

ShoppingCore/Views/Shared/_Cart.cshtml
@model ShoppingCore.Models.ProductDetail

<ul>
    <li class="cart"><a asp-controller="Shopping" asp-action="Cart">Your cart: <b>@Model.count items</b> @*(<span class='money'>$0.00</span> in total)*@</a></li>
</ul>

ShoppingCore/Views/Shared/_Catalog.cshtml
@model IEnumerable<ShoppingCore.Models.Tbl_Product>



    

ShoppingCore/Views/Shared/_quickView.cshtml
@model ShoppingCore.Models.Tbl_Product


<div class="main-content-wrapper" style="padding-bottom: 420px;">

    <!-- BEGIN .catalog -->
    <div class="catalog">
        <!-- BEGIN .quick-shop -->
        <div class="items-wrapper">
            <div class="items" id="products">

                <div class="lightbox"></div>
                <div class="quick-shop" style="position: fixed; left: 17%; top:13%; display: block;">
                    <div class="content">
                        <div class="image-resize-container">
                            <div class="image-wrapper-1">
                                <div class="image">
                                    <div class="image-overlay-1 trans-1">
                                        <table>
                                            <tr>
                                                <td>
                                                    <a href="/Home/ProductDetails/@Model.ProductId" class="button-1 custom-font-1 trans-1"><span>View this item in full view</span></a>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                    <a href="products/striped-oak-wood-bed.html"><img src="@Url.Content("/ProductImage/" + Model.ProductImage)" style="height: 344px;position: absolute;left: -143px;top: 0px;" class="product-image-resizable-344x344" alt="Image" /></a>
                                </div>
                            </div>
                        </div>
                        <div class="text">
                            <div id="product-100174820">
                                <h2 class="custom-font-1"><a href="products/striped-oak-wood-bed.html">@Model.ProductName</a></h2>
                                <div class="price custom-font-1">
                                    <p class="current-price"></p>
                                    <p><s class="old-price"></s></p>
                                    @if (User.Identity.IsAuthenticated)
                                    {
                                        <a href="javascript:void(0)" onclick="AddtoCart ('@Model.ProductId')" class="button-3 custom-font-1 trans-1 product-purchase-btn"><span>Add to cart</span></a>
                                    }
                                    else
                                    {
                                        <a asp-controller="Shopping" asp-action="AddProductToCart1" asp-route-itemId="@Model.ProductId" class="button-3 custom-font-1 trans-1 product-purchase-btn"><span>Add to cart</span></a>
                                    }

                                    <div class="clear"></div>
                                </div>

                                <div class="description">
                                    <div class="items">
                                        <div class="item">
                                            @Html.Raw("<span color='white' style='position: absolute;'>" + @Model.Description + "</span>")
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="clear"></div>
                        <a href="#" class="close"></a>
                    </div>
                    <!-- END .quick-shop -->
                </div>
            </div>
        </div>
    </div>
</div>